// QB5 spatial construct variants: 7 families × 8 archetypes, all with inline SVG diagrams.
(() => {
  'use strict';
  const E=window.QB5E;if(!E)return;const {register,set,setNum,mod}=E;
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const svg=(inner,label='空間題圖示',w=360,h=220)=>`<svg class="qb5-spatial-svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(label)}" xmlns="http://www.w3.org/2000/svg">${inner}</svg>`;
  function arr(x1,y1,x2,y2,label=''){const dx=x2-x1,dy=y2-y1,L=Math.hypot(dx,dy)||1,ux=dx/L,uy=dy/L,px=-uy,py=ux,ax=x2-ux*10,ay=y2-uy*10;return `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="currentColor" stroke-width="3"/><polygon points="${x2},${y2} ${ax+px*7},${ay+py*7} ${ax-px*7},${ay-py*7}" fill="currentColor"/>${label?`<text x="${(x1+x2)/2}" y="${(y1+y2)/2-7}" text-anchor="middle" font-size="12">${esc(label)}</text>`:''}`;}
  function pathSvg(steps){let x=80,y=150,inner=`<circle cx="${x}" cy="${y}" r="6" fill="currentColor"/><text x="${x-10}" y="${y+22}" font-size="12">S</text>`;for(const [dx,dy,label] of steps){const nx=x+Math.sign(dx)*45,ny=y-Math.sign(dy)*45;inner+=arr(x,y,nx,ny,label);x=nx;y=ny;}inner+=`<circle cx="${x}" cy="${y}" r="7" fill="none" stroke="currentColor" stroke-width="3"/><text x="${x+9}" y="${y+5}" font-size="12">E</text>`;return svg(inner,'方格位移示意圖');}
  function axes(point,axis,c=0){const sx=x=>180+x*18,sy=y=>110-y*18;let m='';if(axis==='y')m='<line x1="180" y1="15" x2="180" y2="205" stroke="currentColor" stroke-width="2" stroke-dasharray="6 5"/>';if(axis==='x')m='<line x1="20" y1="110" x2="340" y2="110" stroke="currentColor" stroke-width="2" stroke-dasharray="6 5"/>';if(axis==='y=x')m='<line x1="85" y1="205" x2="275" y2="15" stroke="currentColor" stroke-width="2" stroke-dasharray="6 5"/>';if(axis==='y=-x')m='<line x1="85" y1="15" x2="275" y2="205" stroke="currentColor" stroke-width="2" stroke-dasharray="6 5"/>';if(axis==='x=c')m=`<line x1="${sx(c)}" y1="15" x2="${sx(c)}" y2="205" stroke="currentColor" stroke-width="2" stroke-dasharray="6 5"/>`;if(axis==='y=c')m=`<line x1="20" y1="${sy(c)}" x2="340" y2="${sy(c)}" stroke="currentColor" stroke-width="2" stroke-dasharray="6 5"/>`;return svg(`<line x1="20" y1="110" x2="340" y2="110" stroke="currentColor" opacity=".25"/><line x1="180" y1="15" x2="180" y2="205" stroke="currentColor" opacity=".25"/>${m}<circle cx="${sx(point[0])}" cy="${sy(point[1])}" r="7" fill="currentColor"/><text x="${sx(point[0])+9}" y="${sy(point[1])-8}" font-size="12">P(${point[0]},${point[1]})</text>`,'座標鏡射圖');}
  function compass(angle,label){const r=(angle-90)*Math.PI/180,cx=180,cy=110,x=cx+Math.cos(r)*67,y=cy+Math.sin(r)*67;return svg(`<circle cx="180" cy="110" r="78" fill="none" stroke="currentColor" opacity=".3"/><text x="180" y="20" text-anchor="middle">N 0°</text><text x="337" y="115" text-anchor="end">E 90°</text><text x="180" y="214" text-anchor="middle">S 180°</text><text x="20" y="115">W 270°</text>${arr(cx,cy,x,y,'起始')}<text x="180" y="108" text-anchor="middle" font-size="11">${esc(label)}</text>`,'方位旋轉圖');}
  function rectSvg(L,W,cuts=[]){const x=70,y=35,w=220,h=140;let z=`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="none" stroke="currentColor" stroke-width="3"/><text x="180" y="198" text-anchor="middle">長 ${L}</text><text x="48" y="108" text-anchor="middle" transform="rotate(-90 48 108)">寬 ${W}</text>`;for(const c of cuts)z+=`<rect x="${x+c.x*w}" y="${y+c.y*h}" width="${c.w*w}" height="${c.h*h}" fill="currentColor" fill-opacity=".18" stroke="currentColor" stroke-dasharray="5 4"/>`;return svg(z,'長方形裁切圖');}
  function stackSvg(g){const R=g.length,C=g[0].length,cell=46,ox=180-C*cell/2,oy=105-R*cell/2;let z='';for(let r=0;r<R;r++)for(let c=0;c<C;c++){const x=ox+c*cell,y=oy+r*cell;z+=`<rect x="${x}" y="${y}" width="${cell}" height="${cell}" fill="none" stroke="currentColor"/><text x="${x+cell/2}" y="${y+cell/2+6}" text-anchor="middle" font-size="18">${g[r][c]}</text>`;}z+='<text x="180" y="205" text-anchor="middle" font-size="12">俯視圖：數字＝該格柱高</text>';return svg(z,'方塊柱俯視高度圖');}
  function faces(g){let top=0,side=0,R=g.length,C=g[0].length;for(let r=0;r<R;r++)for(let c=0;c<C;c++){const h=g[r][c];if(h<=0)continue;top++;for(const [dr,dc] of [[1,0],[-1,0],[0,1],[0,-1]]){const rr=r+dr,cc=c+dc,nh=rr<0||cc<0||rr>=R||cc>=C?0:g[rr][cc];side+=Math.max(0,h-nh);}}return top+side;}
  function scaleSvg(shape,a,b,s){return shape==='segment'?svg(`<line x1="70" y1="110" x2="290" y2="110" stroke="currentColor" stroke-width="5"/><text x="180" y="88" text-anchor="middle">原長 ${a}</text><text x="180" y="158" text-anchor="middle">縮放倍率 ${s}</text>`,'比例縮放線段圖'):svg(`<rect x="90" y="55" width="180" height="110" fill="none" stroke="currentColor" stroke-width="3"/><text x="180" y="190" text-anchor="middle">原長 ${a}</text><text x="64" y="110" text-anchor="middle" transform="rotate(-90 64 110)">原寬 ${b}</text><text x="180" y="28" text-anchor="middle">縮放倍率 ${s}</text>`,'比例縮放矩形圖');}
  function bfs(N,S,T,B){const q=[[...S,0]],seen=new Set([S.join(',')]);for(let i=0;i<q.length;i++){const [r,c,d]=q[i];if(r===T[0]&&c===T[1])return d;for(const [dr,dc] of [[1,0],[-1,0],[0,1],[0,-1]]){const rr=r+dr,cc=c+dc,k=`${rr},${cc}`;if(rr<0||cc<0||rr>=N||cc>=N||B.has(k)||seen.has(k))continue;seen.add(k);q.push([rr,cc,d+1]);}}return null;}
  function gridSvg(N,S,T,B){const cell=Math.floor(180/N),ox=90,oy=20;let z='';for(let r=0;r<N;r++)for(let c=0;c<N;c++){const k=`${r},${c}`,x=ox+c*cell,y=oy+r*cell,b=B.has(k);z+=`<rect x="${x}" y="${y}" width="${cell}" height="${cell}" fill="${b?'currentColor':'none'}" fill-opacity="${b?'.2':'0'}" stroke="currentColor" stroke-opacity=".25"/>`;}const p=a=>[ox+a[1]*cell+cell/2,oy+a[0]*cell+cell/2],[sx,sy]=p(S),[tx,ty]=p(T);z+=`<circle cx="${sx}" cy="${sy}" r="6" fill="currentColor"/><text x="${sx+8}" y="${sy-8}">S</text><circle cx="${tx}" cy="${ty}" r="7" fill="none" stroke="currentColor" stroke-width="3"/><text x="${tx+8}" y="${ty-8}">E</text><text x="180" y="215" text-anchor="middle" font-size="12">只能上下左右；灰格不可通行</text>`;return svg(z,'格線最短路徑圖');}
  const finish=(q,type,visual)=>{q.visual=visual;q.diagramType=type;q.presentationMode='spatial-diagram';};

  register('grid-displacement',(q,{n,v,t})=>{const x=2+mod(n,6),y=2+mod(n*2,6),d=1+t;let s;if(v===0)s=[[3+d,0],[0,2+d]];else if(v===1)s=[[-2-d,0],[0,3+d]];else if(v===2)s=[[2+d,0],[0,-1-d],[1,0]];else if(v===3)s=[[0,3+d],[-2,0],[0,-1]];else if(v===4)s=[[2,0],[0,2],[-1-d,0]];else if(v===5)s=[[-2,0],[0,-2],[3+d,0]];else if(v===6)s=[[1+d,0],[0,1+d],[-1,0],[0,2]];else s=[[0,-2-d],[2+d,0],[0,1]];let dx=0,dy=0;s.forEach(a=>{dx+=a[0];dy+=a[1];});const ex=x+dx,ey=y+dy,txt=s.map(([a,b])=>a?`${a>0?'向右':'向左'} ${Math.abs(a)} 格`:`${b>0?'向上':'向下'} ${Math.abs(b)} 格`).join('，再');q.q=`棋子從 (${x}, ${y}) 出發，依序${txt}。終點座標是？`;set(q,`(${ex}, ${ey})`,[`(${ex+1}, ${ey})`,`(${ex}, ${ey-1})`,`(${ey}, ${ex})`]);q.e=`依步驟分別更新 x、y，最後得到 (${ex}, ${ey})。`;finish(q,'grid-displacement',pathSvg(s.map(([a,b])=>[a,b,`${Math.abs(a||b)} 格`])));});

  register('mirror-coordinate',(q,{n,v})=>{const x=2+mod(n,5),y=1+mod(n*2,5),c=1+mod(n,2);let a,axis,p;if(v===0){a=[-x,y];axis='y';p=`點 (${x}, ${y}) 對 y 軸鏡射後的座標是？`;}else if(v===1){a=[x,-y];axis='x';p=`點 (${x}, ${y}) 對 x 軸鏡射後的座標是？`;}else if(v===2){a=[-x,-y];axis='origin';p=`點 (${x}, ${y}) 以原點為中心旋轉 180° 後的座標是？`;}else if(v===3){a=[y,x];axis='y=x';p=`點 (${x}, ${y}) 對直線 y=x 鏡射後的座標是？`;}else if(v===4){a=[-y,-x];axis='y=-x';p=`點 (${x}, ${y}) 對直線 y=−x 鏡射後的座標是？`;}else if(v===5){a=[2*c-x,y];axis='x=c';p=`點 (${x}, ${y}) 對直線 x=${c} 鏡射後的座標是？`;}else if(v===6){a=[x,2*c-y];axis='y=c';p=`點 (${x}, ${y}) 對直線 y=${c} 鏡射後的座標是？`;}else {a=[-y,x];axis='y';p=`點 (${x}, ${y}) 先對 y 軸鏡射，再逆時針旋轉 90°。最後座標是？`;}q.q=p;set(q,`(${a[0]}, ${a[1]})`,[`(${-a[0]}, ${a[1]})`,`(${a[0]}, ${-a[1]})`,`(${a[1]}, ${a[0]})`]);q.e=`依指定幾何變換逐步更新座標，得到 (${a[0]}, ${a[1]})。`;finish(q,'mirror-coordinate',axes([x,y],axis,c));});

  register('viewpoint-heading',(q,{n,v,t})=>{const start=mod(n*35+v*20,360);let end,desc;if(v===0){const a=45+45*t;end=mod(start+a,360);desc=`順時針 ${a}°`;}else if(v===1){const a=45+45*t;end=mod(start-a,360);desc=`逆時針 ${a}°`;}else if(v===2){const b=45+45*t;end=mod(start+90-b,360);desc=`先順時針 90°，再逆時針 ${b}°`;}else if(v===3){const a=1+t;end=mod(start+90*a,360);desc=`順時針 ${a} 個四分之一圈`;}else if(v===4){end=mod(start+180,360);desc='轉向正後方（180°）';}else if(v===5){end=mod(start+270,360);desc='順時針 270°';}else if(v===6){end=mod(start-135,360);desc='逆時針 135°';}else{end=mod(start+225,360);desc='順時針 225°';}q.q=`方位角以正北 0°、順時針增加。指針起始在 ${start}°，${desc}。最後方位角是多少？`;set(q,`${end}°`,[`${mod(end+45,360)}°`,`${mod(end-45,360)}°`,`${mod(end+180,360)}°`]);q.e=`依旋轉方向加減角度，換成 0°–359° 等價角後得到 ${end}°。`;finish(q,'heading-rotation',compass(start,desc));});

  register('rectangle-cut',(q,{n,v,t})=>{const L=8+mod(n,8),W=6+mod(n*2,6);let c,cuts,p,ex;if(v===0){const s=1+t;c=L*(W-s);cuts=[{x:0,y:0,w:1,h:s/W}];p=`長 ${L}、寬 ${W} 的長方形，沿整條長邊裁去寬 ${s} 的紙條。剩餘面積？`;ex=`${L}×${W-s}=${c}。`;}else if(v===1){const a=2+t,b=2;c=L*W-a*b;cuts=[{x:0,y:0,w:a/L,h:b/W}];p=`長 ${L}、寬 ${W} 的長方形，從一個角裁去 ${a}×${b} 的小長方形。剩餘面積？`;ex=`${L*W}−${a*b}=${c}。`;}else if(v===2){const s=1+t;c=(L-s)*(W-s);cuts=[{x:0,y:0,w:1,h:s/W},{x:0,y:0,w:s/L,h:1}];p=`長 ${L}、寬 ${W} 的長方形，沿上邊與左邊各裁去寬 ${s} 的整條紙帶；重疊角只裁一次。中央剩餘面積？`;ex=`${L-s}×${W-s}=${c}。`;}else if(v===3){c=L*W/2;cuts=[{x:0,y:0,w:.5,h:1}];p=`長 ${L}、寬 ${W} 的長方形沿中線切成面積相等的兩半，移除其中一半。剩餘面積？`;ex=`${L*W}÷2=${c}。`;}else if(v===4){const a=2,b=1+t;c=L*W-a*b;cuts=[{x:.5-a/(2*L),y:0,w:a/L,h:b/W}];p=`長 ${L}、寬 ${W} 的長方形，上邊中央挖去 ${a}×${b} 的矩形缺口。剩餘面積？`;ex=`${L*W}−${a*b}=${c}。`;}else if(v===5){const s=2;c=(L-s)*W;cuts=[{x:1-s/L,y:0,w:s/L,h:1}];p=`長 ${L}、寬 ${W} 的長方形，右側整條裁去寬 ${s}。剩餘面積？`;ex=`${L-s}×${W}=${c}。`;}else if(v===6){const a=2,b=2;c=L*W-2*a*b;cuts=[{x:0,y:0,w:a/L,h:b/W},{x:1-a/L,y:1-b/W,w:a/L,h:b/W}];p=`長 ${L}、寬 ${W} 的長方形，從兩個相對角各裁去 ${a}×${b}。剩餘面積？`;ex=`${L*W}−2×${a*b}=${c}。`;}else{const s=1;c=(L-2*s)*(W-2*s);cuts=[{x:0,y:0,w:1,h:s/W},{x:0,y:1-s/W,w:1,h:s/W},{x:0,y:0,w:s/L,h:1},{x:1-s/L,y:0,w:s/L,h:1}];p=`長 ${L}、寬 ${W} 的長方形四周都裁去寬 ${s} 的邊框。中央面積？`;ex=`${L-2*s}×${W-2*s}=${c}。`;}q.q=p;q.e=ex;setNum(q,c,[-2,-1,1]);finish(q,'rectangle-cut',rectSvg(L,W,cuts));});

  register('stack-hidden',(q,{n,v,t})=>{const b=1+mod(n,3),patterns=[[[b,b+1],[b+2,b]],[[b+2,b],[b,b+2]],[[b,b+1],[b+1,b+2]],[[b+2,b+1],[b,0]],[[b+1,b+1],[b+1,b+1]],[[b+2,0],[b+1,b]],[[b,b+2],[b+2,b]],[[b+2,b+1],[b+1,b]]],g=patterns[v].map(r=>r.map(x=>x?x+t:0)),c=faces(g);q.q='俯視圖中的數字表示該格直立方塊柱的高度。所有方塊都是單位立方體、相鄰柱貼合、底面貼地不計。整個造型共有多少個外露面？';q.e=`逐格計算頂面與四側高差形成的外露面，合計 ${c} 個。`;setNum(q,c,[-2,-1,1]);finish(q,'stack-surface',stackSvg(g));});

  register('scale-drawing',(q,{n,v})=>{const a=3+mod(n,7),b=2+mod(n*2,5);let s=2+mod(v,3),c,p,shape='rect';if(v===0){shape='segment';c=a*s;p=`圖中線段原長 ${a} 格，等比例放大 ${s} 倍後，新長度是多少格？`;}else if(v===1){c=a*s;p=`矩形原長 ${a}、寬 ${b}，等比例放大 ${s} 倍。新長是多少？`;}else if(v===2){c=b*s;p=`矩形原長 ${a}、寬 ${b}，等比例放大 ${s} 倍。新寬是多少？`;}else if(v===3){c=2*(a+b)*s;p=`矩形原長 ${a}、寬 ${b}，等比例放大 ${s} 倍。放大後周長是多少？`;}else if(v===4){c=a*b*s*s;p=`矩形原長 ${a}、寬 ${b}，等比例放大 ${s} 倍。放大後面積是多少？`;}else if(v===5){shape='segment';c=a;p=`一條線段放大 ${s} 倍後長 ${a*s} 格。原長是多少格？`;}else if(v===6){s=1;c=a+b;p=`矩形長 ${a}、寬 ${b}。若圖形只做平移、不縮放，長與寬的和仍是多少？`;}else{c=(a*s)*(b*s);p=`矩形原長 ${a}、寬 ${b}，長與寬都變成原來 ${s} 倍。新面積是多少？`;}q.q=p;q.e=`依題目指定的線性縮放關係計算，得到 ${c}。`;setNum(q,c,[-2,-1,1]);finish(q,'scale-drawing',scaleSvg(shape,a,b,s));});

  register('shortest-grid-path',(q,{n,v,t})=>{const N=t===0?6:t===1?7:8,S=[N-1,0],T=[0,N-1],B=new Set(),gap=1+mod(n+v,N-2);if(v===0){for(let r=1;r<N-1;r++)if(r!==gap)B.add(`${r},2`);}else if(v===1){const row=Math.min(3,N-2);for(let c=1;c<N-1;c++)if(c!==gap)B.add(`${row},${c}`);}else if(v===2){for(let r=1;r<N-2;r++)B.add(`${r},2`);for(let c=2;c<N-1;c++)B.add(`${N-3},${c}`);B.delete(`${gap},2`);}else if(v===3){for(let i=1;i<N-1;i++)if(i!==gap)B.add(`${i},${i}`);}else if(v===4){for(let c=1;c<N-1;c+=2)B.add(`${N-3},${c}`);for(let r=1;r<N-3;r+=2)B.add(`${r},3`);}else if(v===5){const col=N-3;for(let r=1;r<N-1;r++)if(r!==gap)B.add(`${r},${col}`);}else if(v===6){const row=N-4;for(let c=1;c<N-1;c++)if(c!==gap)B.add(`${row},${c}`);for(let r=1;r<row;r++)if(r!==gap)B.add(`${r},2`);}else{for(let i=1;i<N-1;i++){const col=i%2===0?2:N-3;B.add(`${i},${col}`);}}B.delete(S.join(','));B.delete(T.join(','));let c=bfs(N,S,T,B);if(c==null){B.clear();const col=Math.floor(N/2);for(let r=1;r<N-1;r++)if(r!==gap)B.add(`${r},${col}`);c=bfs(N,S,T,B);}q.q='從 S 走到 E，每次只能上下左右移動 1 格，灰色方格不可通行。最少需要走幾步？';q.e=`依障礙物尋找最短可行路徑，最少需要 ${c} 步。`;setNum(q,c,[-1,1,2]);q.diagramData={size:N,start:S,end:T,blocked:[...B],shortest:c};finish(q,'grid-shortest-path',gridSvg(N,S,T,B));});
})();