const fs=require('fs');
const path=require('path');
const vm=require('vm');
const assert=require('assert');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'dist','qb5-export');fs.mkdirSync(OUT,{recursive:true});
const store={},window={addEventListener(){}};
const context={window,document:{getElementById(){return null;}},localStorage:{getItem(k){return store[k]??null;},setItem(k,v){store[k]=v;},removeItem(k){delete store[k];}},console,Math,JSON,Set,Map,Array,Number,String,Object,Date,RegExp};vm.createContext(context);
const runtimeFiles=['question-bank.js','qb5-core.js','qb5-verbal.js','qb5-fluid.js','qb5-spatial.js','qb5-memory.js','qb5-speed.js','qb5-quant.js','qb5-parameter-diversity.js','qb5-ordering-diversity-fix.js','qb5-form-equivalence.js','qb5-finalize.js','qb5-compact-bank.js','qb5-verbal-surface-expansion.js','natural-language-v2.js','question-language-finalize.js','answer-position-balance.js','answer-quality.js','memory-integrity.js','hard-construct-integrity.js','processing-speed-integrity.js','full-bank-polish.js','memory-usability.js','spatial-reliability.js','spatial-task-refinement.js','presentation-clarity.js','calibration/anchor-core.js','qb5-42-form.js'];
for(const file of runtimeFiles)vm.runInContext(fs.readFileSync(path.join(ROOT,file),'utf8'),context,{filename:file});
const bank=window.IQ_QUESTION_BANK,meta=window.IQ_BANK_META,validation=window.IQ_BANK_VALIDATION,qb5=window.IQ_QB5;
assert.ok(Array.isArray(bank));assert.strictEqual(bank.length,2058);assert.strictEqual(meta.version,'QB-2026.09.5');assert.strictEqual(meta.revision,'5.0');assert.strictEqual(meta.semanticTemplates,294);assert.strictEqual(meta.surfaceVariantsPerConstruct,7);assert.strictEqual(meta.bankTopology,'294x7=2058');assert.strictEqual(meta.selectedItems,42);assert.strictEqual(validation.uniqueTaskSignatures,2058);assert.strictEqual(meta.naturalLanguageRevision,'NL-2026.09.3');assert.strictEqual(meta.languageStyle,'direct-taiwan-zh-hant');assert.strictEqual(meta.memoryIntegrity,'WMI-2026.09.1');assert.strictEqual(meta.hardConstructIntegrity,'HCI-2026.09.1');assert.strictEqual(meta.processingSpeedIntegrity,'PSI-2026.09.1');assert.strictEqual(meta.fullBankSweep,'FBQ-2026.09.1');assert.strictEqual(meta.fullBankPolish,'FBP-2026.09.2');assert.strictEqual(meta.memoryUsability,'MUI-2026.09.2');assert.strictEqual(meta.spatialReliability,'SRI-2026.09.1');assert.strictEqual(meta.spatialTaskRefinement,'STR-2026.09.2');assert.strictEqual(window.IQ_QUESTIONS.length,42);assert.strictEqual(window.IQ_42_FORM.items,42);assert.strictEqual(window.IQ_42_FORM.anchorReserve.count,6);assert.strictEqual(meta.reservedCalibrationAnchors,6);assert.strictEqual(meta.activeProductionItems,2052);assert.strictEqual(window.IQ_SPATIAL_TASK_REFINEMENT?.total,168);assert.strictEqual(window.IQ_SPATIAL_TASK_REFINEMENT?.scaleDrawing,56);
const reservedIds=new Set(window.IQ_42_FORM.anchorReserve.ids);assert.ok(window.IQ_QUESTIONS.every(q=>!reservedIds.has(q.id)),'formal form must exclude reserved calibration anchors');
assert.ok(bank.every(q=>Number.isFinite(Number(q.formLoad))&&q.formLoad>0));
const marker=/·\d+$/,floatArtifact=/-?\d+\.\d{6,}/;for(const q of bank){assert.ok(Array.isArray(q.o)&&q.o.length===4);assert.strictEqual(new Set(q.o.map(String)).size,4);assert.strictEqual(String(q.o[q.a]),String(q.correctContent));assert.ok(!q.o.some(x=>marker.test(String(x))),`${q.id}: synthetic marker`);assert.ok(![q.q,q.e,...q.o].some(x=>floatArtifact.test(String(x??''))),`${q.id}: float artifact`);}
const positions=[0,0,0,0];for(const q of bank)positions[q.a]++;assert.strictEqual(positions.reduce((a,b)=>a+b,0),2058);assert.ok(Math.max(...positions)-Math.min(...positions)<=1,`answer positions must be near-even: ${positions.join('/')}`);
const spatial=bank.filter(q=>q.d==='視覺空間');assert.strictEqual(spatial.length,392);assert.ok(spatial.every(q=>String(q.visual||'').includes('<svg')&&String(q.visual||'').includes('preserveAspectRatio="xMidYMid meet"')&&q.spatialReliability==='SRI-2026.09.1'));
const speed=bank.filter(q=>q.d==='處理速度');assert.strictEqual(speed.length,392);assert.ok(speed.every(q=>Number(q.limit)===18&&q.processingSpeedIntegrity==='PSI-2026.09.1'));
const memory=bank.filter(q=>q.d==='工作記憶');assert.strictEqual(memory.length,392);
const memoryFamilies=['memory-position','memory-pair','memory-filter','memory-relative','memory-reorder','memory-update'];const memoryUsabilityItems=bank.filter(q=>memoryFamilies.includes(q.taskFamily));assert.strictEqual(memoryUsabilityItems.length,336);assert.ok(memoryUsabilityItems.every(q=>q.memoryUsability==='MUI-2026.09.2'&&q.limit==null));assert.ok(memory.every(q=>!/\d{3,}/.test(String(q.stim||''))));
const matrixClarityItems=bank.filter(q=>q.taskFamily==='matrix-difference'&&q.matrixClarityVersion==='MC-2026.09.1');assert.strictEqual(matrixClarityItems.length,56);assert.ok(matrixClarityItems.every(q=>q.cells?.length===12&&q.cells[11]==='?'));
const finalSig=q=>JSON.stringify([q.q,q.stim||'',q.cells||[],q.visual||'',[...q.o].map(String).sort()]);assert.strictEqual(new Set(bank.map(finalSig)).size,2058);
const perSemantic=new Map();for(const q of bank)perSemantic.set(q.semanticKey,(perSemantic.get(q.semanticKey)||0)+1);assert.strictEqual(perSemantic.size,294);assert.ok([...perSemantic.values()].every(n=>n===7));
for(const domain of ['語文理解','流體推理','視覺空間','工作記憶','處理速度','量化推理']){const group=window.IQ_QUESTIONS.filter(q=>q.d===domain);assert.strictEqual(group.length,7);assert.strictEqual(new Set(group.map(q=>q.taskFamily)).size,7);assert.strictEqual(group.filter(q=>q.difficulty==='easy').length,2);assert.strictEqual(group.filter(q=>q.difficulty==='medium').length,3);assert.strictEqual(group.filter(q=>q.difficulty==='hard').length,2);}
const exportedAt=new Date().toISOString();
const exportMeta={...meta,exportedAt,sourceBranch:'feature/cognitive-iq-lab-v6',runtimeOrder:runtimeFiles,answerPositionCounts:positions,spatialSvgItems:spatial.length,processingSpeedItems:speed.length,workingMemoryItems:memory.length,memoryUsabilityItems:memoryUsabilityItems.length,matrixClarityItems:matrixClarityItems.length,uniqueConcreteItems:2058,productionFormItems:42,reservedCalibrationAnchorIds:[...reservedIds],anchorReserve:window.IQ_42_FORM.anchorReserve,formBlueprint:window.IQ_42_FORM||null,formEquivalenceVersion:window.QB5_FORM_EQUIVALENCE?.version||null,naturalLanguage:window.IQ_NATURAL_LANGUAGE||null,memoryIntegrity:window.IQ_MEMORY_INTEGRITY||null,hardConstructIntegrity:window.IQ_HARD_CONSTRUCT_INTEGRITY||null,processingSpeedIntegrity:window.IQ_PROCESSING_SPEED_INTEGRITY||null,memoryUsability:window.IQ_MEMORY_USABILITY||null,spatialReliability:window.IQ_SPATIAL_RELIABILITY||null,spatialTaskRefinement:window.IQ_SPATIAL_TASK_REFINEMENT||null,fullBankSweep:window.IQ_FULL_BANK_SWEEP||null,fullBankPolish:window.IQ_FULL_BANK_POLISH||null,compactBank:window.IQ_COMPACT_BANK||null,note:'QB5 final export: 2,058 unique items = 294 construct variants × 7 concrete surfaces; 42-item forms cover all seven task families in every domain; six medium items are reserved as stable unscored calibration anchors and are excluded from scored forms; Working Memory Integrity v1; Hard Construct Integrity v1; Processing Speed Integrity v1; Memory Usability Integrity v2; Spatial Reliability Integrity v1 plus Spatial Task Refinement v2 for path, mirror, and scale/translation tasks; matrix-difference items provide three complete example rows; Safari-safe SVG visuals.'};
fs.writeFileSync(path.join(OUT,'QB5-2058-balanced-bank.json'),JSON.stringify({meta:exportMeta,validation,qb5,items:bank},null,2));fs.writeFileSync(path.join(OUT,'QB5-2058-items.json'),JSON.stringify(bank,null,2));
function cell(v){if(v==null)return '';const s=typeof v==='string'?v:JSON.stringify(v);return `"${s.replaceAll('"','""')}"`;}
const headers=['id','bankVersion','bankRevision','constructRevision','constructVariant','surfaceVariant','complexityScore','formLoad','domain','difficulty','taskFamily','taskLabel','semanticKey','model','type','limit','question','optionA','optionB','optionC','optionD','answerIndex','answerLetter','correctAnswer','explanation','stimulus','cells','visual','diagramType','diagramData','source'];const rows=[headers.map(cell).join(',')];
for(const q of bank){const values=[q.id,q.bankVersion,q.bankRevision,q.constructRevision,q.constructVariant,q.surfaceVariant??'',q.complexityScore,q.formLoad??'',q.d,q.difficulty,q.taskFamily,q.taskLabel,q.semanticKey,q.model,q.type,q.limit??'',q.q,q.o?.[0]??'',q.o?.[1]??'',q.o?.[2]??'',q.o?.[3]??'',q.a,String.fromCharCode(65+q.a),q.o?.[q.a]??'',q.e,q.stim??'',q.cells??'',q.visual??'',q.diagramType??'',q.diagramData??'',q.source??''];rows.push(values.map(cell).join(','));}fs.writeFileSync(path.join(OUT,'QB5-2058-balanced-bank.csv'),rows.join('\n'));
const readme=`Cognitive IQ Lab — QB5 Final Bank\n\nVersion: ${meta.version}\nRevision: ${meta.revision}\nTopology: 294 construct variants × 7 concrete surfaces = 2,058 items\nProduction form: 42 scored items = 6 domains × 7 task families\nReserved calibration anchors: ${reservedIds.size} unscored medium items\nActive scored-form pool: ${meta.activeProductionItems}\nDifficulty per domain: 2 easy / 3 medium / 2 hard\nNatural language: ${meta.naturalLanguageRevision}\nWorking-memory integrity: ${meta.memoryIntegrity}\nHard construct integrity: ${meta.hardConstructIntegrity}\nProcessing-speed integrity: ${meta.processingSpeedIntegrity}\nMemory usability: ${meta.memoryUsability}\nSpatial reliability: ${meta.spatialReliability}\nSpatial task refinement: ${meta.spatialTaskRefinement}\nFull-bank polish: ${meta.fullBankPolish}\nItems: ${bank.length}\nTask families: ${meta.taskFamilies}\nConstruct variants: ${meta.semanticTemplates}\nConcrete surfaces per construct: ${meta.surfaceVariantsPerConstruct}\nUnique final concrete signatures: 2058\nSpatial SVG items: ${spatial.length}\nSpatial refined path/mirror/scale items: ${window.IQ_SPATIAL_TASK_REFINEMENT.total}\nMatrix clarity items: ${matrixClarityItems.length}\nWorking-memory items: ${memory.length}\nProcessing-speed timed items: ${speed.length}\nMemory-usability items: ${memoryUsabilityItems.length}\nAnswer positions A/B/C/D: ${positions.join(' / ')}\nExported: ${exportedAt}\n\n294 is the number of construct variants across 42 task families, not 294 independent cognitive abilities. Every construct retains seven concrete item surfaces. Each 42-item production form contains all seven task families in every cognitive domain. Six stable medium-difficulty items are reserved for the unscored calibration anchor block and do not appear in the scored 42-item form. Coordinate path tasks require path integration from a known start instead of direct endpoint-coordinate reading; mirror diagrams include labeled/ticked axes; scale tasks explicitly state whether translation occurs and provide the translation vector when it does. Matrix tasks provide three complete example rows before the target row.\n\nThis remains an uncalibrated experimental cognitive-play bank. Difficulty and formLoad are design metrics, not population-calibrated psychometric parameters.\n`;fs.writeFileSync(path.join(OUT,'README.txt'),readme);
console.log(`QB5 export PASS: ${bank.length} items / ${meta.semanticTemplates} constructs / 7 surfaces each / ${window.IQ_QUESTIONS.length}-item forms / ${reservedIds.size} reserved anchors`);console.log(`A/B/C/D: ${positions.join('/')}; Spatial SVG: ${spatial.length}; spatial refinements: ${window.IQ_SPATIAL_TASK_REFINEMENT.total}; matrix clarity: ${matrixClarityItems.length}; Timed speed: ${speed.length}; Working memory: ${memory.length}`);console.log(`Output: ${OUT}`);
