const fs=require('fs');
const path=require('path');
const vm=require('vm');
const assert=require('assert');
const ROOT=path.resolve(__dirname,'..');
const OUT=path.join(ROOT,'dist','qb5-export');
fs.mkdirSync(OUT,{recursive:true});
const store={};
const window={addEventListener(){}};
const context={window,document:{getElementById(){return null;}},localStorage:{getItem(k){return store[k]??null;},setItem(k,v){store[k]=v;},removeItem(k){delete store[k];}},console,Math,JSON,Set,Map,Array,Number,String,Object,Date,RegExp};
vm.createContext(context);
const runtimeFiles=['question-bank.js','qb5-core.js','qb5-verbal.js','qb5-fluid.js','qb5-spatial.js','qb5-memory.js','qb5-speed.js','qb5-quant.js','qb5-parameter-diversity.js','qb5-ordering-diversity-fix.js','qb5-form-equivalence.js','qb5-finalize.js','natural-language-v2.js','question-language-finalize.js','answer-position-balance.js','answer-quality.js','memory-integrity.js','full-bank-polish.js','presentation-clarity.js'];
for(const file of runtimeFiles)vm.runInContext(fs.readFileSync(path.join(ROOT,file),'utf8'),context,{filename:file});
const bank=window.IQ_QUESTION_BANK,meta=window.IQ_BANK_META,validation=window.IQ_BANK_VALIDATION,qb5=window.IQ_QB5;
assert.ok(Array.isArray(bank));assert.strictEqual(bank.length,5124);assert.strictEqual(meta.version,'QB-2026.09.5');assert.strictEqual(meta.revision,'5.0');assert.strictEqual(meta.semanticTemplates,294);assert.strictEqual(validation.uniqueTaskSignatures,5124);assert.strictEqual(meta.formEquivalence,'64-candidate-design-load-matching');assert.strictEqual(meta.naturalLanguageRevision,'NL-2026.09.3');assert.strictEqual(meta.languageStyle,'direct-taiwan-zh-hant');
assert.strictEqual(meta.fullBankSweep,'FBQ-2026.09.1');assert.strictEqual(meta.fullBankPolish,'FBP-2026.09.1');assert.strictEqual(meta.memoryIntegrity,'WMI-2026.09.1');
assert.ok(bank.every(q=>Number.isFinite(Number(q.formLoad))&&q.formLoad>0));
const marker=/·\d+$/;const floatArtifact=/-?\d+\.\d{6,}/;
for(const q of bank){assert.ok(Array.isArray(q.o)&&q.o.length===4);assert.strictEqual(new Set(q.o.map(String)).size,4);assert.strictEqual(String(q.o[q.a]),String(q.correctContent));assert.ok(!q.o.some(x=>marker.test(String(x))),`${q.id}: synthetic marker`);assert.ok(![q.q,q.e,...q.o].some(x=>floatArtifact.test(String(x??''))),`${q.id}: float artifact`);}
const positions=[0,0,0,0];for(const q of bank)positions[q.a]++;assert.deepStrictEqual(positions,[1281,1281,1281,1281]);
const spatial=bank.filter(q=>q.d==='視覺空間');assert.strictEqual(spatial.length,1008);assert.ok(spatial.every(q=>String(q.visual||'').includes('<svg')));assert.ok(spatial.every(q=>String(q.visual||'').includes('preserveAspectRatio="xMidYMid meet"')));
const exportedAt=new Date().toISOString();
const exportMeta={...meta,exportedAt,sourceBranch:'feature/cognitive-iq-lab-v6',runtimeOrder:runtimeFiles,answerPositionCounts:positions,spatialSvgItems:spatial.length,uniqueConcreteItems:validation.uniqueTaskSignatures,formEquivalenceVersion:window.QB5_FORM_EQUIVALENCE?.version||null,naturalLanguage:window.IQ_NATURAL_LANGUAGE||null,memoryIntegrity:window.IQ_MEMORY_INTEGRITY||null,fullBankSweep:window.IQ_FULL_BANK_SWEEP||null,fullBankPolish:window.IQ_FULL_BANK_POLISH||null,note:'QB5 final export: 42 families, 294 construct variants, 5,124 unique concrete items, Natural Language v3, working-memory anti-shortcut integrity, full-bank hygiene/polish, construct-linked design difficulty, load-matched forms, and Safari-safe SVG visuals.'};
fs.writeFileSync(path.join(OUT,'QB5-5124-construct-expanded.json'),JSON.stringify({meta:exportMeta,validation,qb5,items:bank},null,2));
fs.writeFileSync(path.join(OUT,'QB5-5124-items.json'),JSON.stringify(bank,null,2));
function cell(v){if(v==null)return '';const s=typeof v==='string'?v:JSON.stringify(v);return `"${s.replaceAll('"','""')}"`;}
const headers=['id','bankVersion','bankRevision','constructRevision','constructVariant','surfaceVariant','complexityScore','formLoad','domain','difficulty','taskFamily','taskLabel','semanticKey','model','type','limit','question','optionA','optionB','optionC','optionD','answerIndex','answerLetter','correctAnswer','explanation','stimulus','cells','visual','diagramType','diagramData','source'];
const rows=[headers.map(cell).join(',')];
for(const q of bank){const values=[q.id,q.bankVersion,q.bankRevision,q.constructRevision,q.constructVariant,q.surfaceVariant??'',q.complexityScore,q.formLoad??'',q.d,q.difficulty,q.taskFamily,q.taskLabel,q.semanticKey,q.model,q.type,q.limit??'',q.q,q.o?.[0]??'',q.o?.[1]??'',q.o?.[2]??'',q.o?.[3]??'',q.a,String.fromCharCode(65+q.a),q.o?.[q.a]??'',q.e,q.stim??'',q.cells??'',q.visual??'',q.diagramType??'',q.diagramData??'',q.source??''];rows.push(values.map(cell).join(','));}
fs.writeFileSync(path.join(OUT,'QB5-5124-construct-expanded.csv'),rows.join('\n'));
const readme=`Cognitive IQ Lab — QB5 Final Bank\n\nVersion: ${meta.version}\nRevision: ${meta.revision}\nNatural language: ${meta.naturalLanguageRevision}\nLanguage style: ${meta.languageStyle}\nWorking-memory integrity: ${meta.memoryIntegrity}\nFull-bank sweep: ${meta.fullBankSweep}\nFull-bank polish: ${meta.fullBankPolish}\nItems: ${bank.length}\nTask families: ${meta.taskFamilies}\nConstruct variants: ${meta.semanticTemplates}\nUnique concrete item signatures: ${validation.uniqueTaskSignatures}\nSpatial SVG items: ${spatial.length}\nAnswer positions A/B/C/D: ${positions.join(' / ')}\nForm equivalence: ${meta.formEquivalence}\nExported: ${exportedAt}\n\nThe 294 count is the number of construct variants across 42 task families. It is not a claim that there are 294 completely independent cognitive abilities. Controlled surface/parameter variants keep all 5,124 concrete items distinct without inflating that count.\n\nNatural Language v3 follows preserve-semantics-first / remove-template-tone / Taiwan-localization principles. Working Memory Integrity v1 removes monotonic-number, ordinal and outlier-code shortcuts from final memory items. Full-bank sweep/polish additionally rejects visible synthetic de-duplication markers, long floating-point artifacts, duplicate options, several known answer-length cues, and other user-facing generator residue.\n\nEach item includes formLoad design metadata. Production forms keep the fixed 6×5 / 2 easy + 2 medium + 1 hard blueprint and choose among 64 legal candidate forms to reduce residual design-load differences. This is an engineering equivalence guardrail, not psychometric equating.\n\nAll 1,008 spatial items include an inline SVG task diagram.\n\nImportant: this remains an uncalibrated experimental cognitive-play bank. Difficulty labels and formLoad are design metrics, not population-calibrated psychometric parameters.\n`;
fs.writeFileSync(path.join(OUT,'README.txt'),readme);
console.log(`QB5 export PASS: ${bank.length} items / ${meta.semanticTemplates} construct variants / ${validation.uniqueTaskSignatures} unique signatures`);console.log(`Natural language: ${meta.naturalLanguageRevision}`);console.log(`Working-memory integrity: ${meta.memoryIntegrity}`);console.log(`Sweep/polish: ${meta.fullBankSweep} / ${meta.fullBankPolish}`);console.log(`A/B/C/D: ${positions.join('/')}`);console.log(`Spatial SVG: ${spatial.length}`);console.log(`Form equivalence: ${meta.formEquivalence}`);console.log(`Output: ${OUT}`);